### ISSUE TITLE
[FEATURE]: Translate i18n texts to German

### ISSUE THREAD

**Issue by herrardo** [empathyco/x-archetype#100]
### How can the project be improved?

Having the text translated to different languages, in this case, German

### How can this be solved?

Create a new file in `x-archetype/src/i18n/messages` named as `de.messages.json` and copy the content from the English file changing the values of the JSON properties.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by KirilCycle** [comment]
Can i make it directly in master branch ?
