### ISSUE TITLE
[FEATURE]: Translate i18n texts to Portuguese 

### ISSUE THREAD

**Issue by herrardo** [empathyco/x-archetype#105]
### How can the project be improved?

Having the text translated to different languages, in this case, Portuguese

### How can this be solved?

Create a new file in x-archetype/src/i18n/messages named as pt.messages.json and copy the content from the English file changing the values of the JSON properties.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by ClaraSantosmf** [comment]
Hey! I'm interested. I will do! s2
