### ISSUE TITLE
[FEATURE]: Translate i18n texts to French

### ISSUE THREAD

**Issue by herrardo** [empathyco/x-archetype#106]
### How can the project be improved?

Having the text translated to different languages, in this case, French

### How can this be solved?

Create a new file in x-archetype/src/i18n/messages named as fr.messages.json and copy the content from the English file changing the values of the JSON properties.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by FuryACE007** [comment]
Hii,
I would like to work on this issue.
